version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - abruere
  labels:
  - "type: Dependencies"
  ignore:
  - dependency-name: intl-messageformat
    versions:
    - "> 4.4.0"
  - dependency-name: socket.io
    versions:
    - ">= 3.a, < 4"
  - dependency-name: socket.io-client
    versions:
    - ">= 3.a, < 4"
  - dependency-name: stripe
    versions:
    - ">= 7.a, < 8"
  - dependency-name: oidc-provider
    versions:
    - 7.1.0
    - 7.1.1
    - 7.1.2
    - 7.1.3
    - 7.2.0
  - dependency-name: jose
    versions:
    - 3.10.0
    - 3.11.1
    - 3.11.3
    - 3.5.4
    - 3.6.0
    - 3.6.1
    - 3.6.2
    - 3.7.0
    - 3.8.0
    - 3.9.0
  - dependency-name: ngrok
    versions:
    - 4.0.0
  - dependency-name: socket.io-client
    versions:
    - 4.0.0
  - dependency-name: knex
    versions:
    - 0.21.17
  - dependency-name: socket.io-redis
    versions:
    - 6.0.1
